version: '2'
services:
    zarnes-app:
        image: zarnes
        external_links:
            - zarnes-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=zarnes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    zarnes-mongodb:
        extends:
            file: mongodb.yml
            service: zarnes-mongodb
