version: '2'
services:
    zarnes-mongodb:
        container_name: zarnes-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/zarnes/mongodb/:/data/db/
